id: P14B28B2A
initial_creation_type: input
source_metadata:
  title: Katok Getse Gyurme Tenpa Gyaltsen
  language: zh
  description: 'Texts by and about Katok Getse Gyurme Tenpa Gyaltsen (kaḥ thog dge
    rtse ''gyur med bstan pa rgyal mtshan, 1954–2018), who was the seventh head of
    the Nyingma tradition:'
  volume:
    8b2432d3d1854515a3028e2d918b0d53:
      title: Prayer of Aspiration for the Buddhist Teachings to Flourish in Taiwan
      parent: Aspiration Prayers
created_at: '2022-03-01T00:14:01.758901'
last_modified_at: '2022-03-01T00:14:01.758904'
